### ISSUE TITLE
Markbot's expectations

### ISSUE THREAD

**Issue by C-G-G** [C-G-G/responsive-typography#1]
I'm almost done but not sure what to do with Markbot's two small expectations:

- Line 22: Expected to see `margin` with a different value inside `body {}` (which currently is 1.3 rem);
- Expected to see the `article p` selector (don't know what to do with it)

@thomasjbradley

**Comment by thomasjbradley** [comment]
- `body` should almost always have a `margin` set to `0`

- The trick to this assignment is consistent use of margins—only on the bottom. So, `article p` should set `margin: 0 0 1.3rem`. Then the media queries should bump that up to `1.4` & `1.5`. The same margin should be applied to the bottom of everything that needs it.
